name: Documentation Update

on:
  repository_dispatch:
    types: [specmatic-core-release]

env:
  SPECMATIC_LATEST_RELEASE_VERSION: ${{ github.event.client_payload.SPECMATIC_LATEST_RELEASE_VERSION }}    

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        repository: burdeamit/gh-dispatch-md
        fetch-depth: 0
        ref: main
        token: ${{ secrets.UPDATE_TOKEN }}
        path: documentation
    - name: Update version in _config.yaml
      run: |
        sed -i "s/latest_release: .*/latest_release: $SPECMATIC_LATEST_RELEASE_VERSION/" documentation/_config.yaml
    - name: Commit and push    
      run: |
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '${{ secrets.USER_EMAIL }}'
        git add .
        git commit -m "Updated Specmatic Documnentation Version To $SPECMATIC_LATEST_RELEASE_VERSION"
        git push
      working-directory: documentation