name: Documentation Update

on:
  repository_dispatch:
    types: [new_release]

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        repository: burdeamit/hello-there-md
        token: ${{ secrets.UPDATE_TOKEN }}
        path: documentation
    - name: Update version in _config.yaml
      run: |
        sed -i "s|latest_release: .*|latest_release: ${{ github.event.client_payload.version }}|" documentation/_config.yaml
    - name: Commit and push    
      run: |
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '${{ secrets.USER_EMAIL }}'
        git add .
        git commit -m "Update version to ${{ github.event.client_payload.version }}"
        git push
      working-directory: documentation